require("./lib/spa.min");
require("./lib/swiper-3.3.1.min");
require("./views/index");
require("./views/home");
require("./views/find");
require("./views/my");
require("./views/exit");
require("./views/guide");
require("./views/detail");
require("./views/register");
//spa应用中默认的参数为:indexView(默认的是引导页)
SPA.config({
	indexView:"guide"
})
